name: Running Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use NodeJS ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
            node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: migrate database
        run: npx prisma migrate dev
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          SECRET_KEY: Th1sS3cR3T
      - name: running seeder
        run: npx prisma db seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          SECRET_KEY: Th1sS3cR3T
      - name: testing
        run: npm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          SECRET_KEY: Th1sS3cR3T

