name: Running Tests
on: [pull_request]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: ". --sarif --output results.sarif || true"
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: shorturl_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use NodeJS ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: migrate database
        run: npm run db:test:reset
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shorturl_test
          SECRET_KEY: Th1sS3cR3T
          DISABLE_SENTRY: true
          DISABLE_TOKEN_CLEANUP: true
      - name: running seeder
        run: npm run db:test:seed
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shorturl_test
          SECRET_KEY: Th1sS3cR3T
          DISABLE_SENTRY: true
          DISABLE_TOKEN_CLEANUP: true
      - name: testing
        run: npm test
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shorturl_test
          SECRET_KEY: Th1sS3cR3T
          DISABLE_SENTRY: true
          DISABLE_TOKEN_CLEANUP: true
